
CREATE TABLE contact (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    MIDDLE_NAME VARCHAR(50),
    BIRTH_DATE DATE,
    PHONE_NUMBER VARCHAR(15),
    EMAIL VARCHAR(100),
    GENDER VARCHAR(1),
    CREDIT_RATING INT
);

CREATE TABLE landing_rate (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    RATE DOUBLE(8, 2) NOT NULL,
    LOAN_INTENT VARCHAR(255) NULL
);

CREATE TABLE crm_deal (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    SOURCE VARCHAR(100),
    LOAN_AMOUNT BIGINT,
    LOAN_DURATION INT NULL,
    RESPONSIBLE_ID INT,
    CONTANT_ID INT,
    COMPANY_ID INT,
    LANDING_RATE_ID INT,
    COMMENT TEXT,
    DATE_CREATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DATE_CLOSED DATETIME NULL,
    STAGE VARCHAR(255) NOT NULL,
    ANNUAL_INCOME DECIMAL(15, 2),
    MONTHLY_SALARY DECIMAL(15, 2),
    LOAN_TYPE VARCHAR(100),
    SCORING_RESULT VARCHAR(50),
    DEAL_RESULT VARCHAR(50),
    STATUS_CREDIT VARCHAR(50),
    
    FOREIGN KEY (CONTANT_ID) REFERENCES contact(ID),
    FOREIGN KEY (LANDING_RATE_ID) REFERENCES landing_rate(RATE_ID)
);

CREATE TABLE company(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    FUL_NAME VARCHAR(255) NOT NULL,
    REPRESENTATIVE_NAME VARCHAR(255) NOT NULL,
    REPRESENTATIVE_LAST_NAME VARCHAR(255) NOT NULL,
    ADDRESS VARCHAR(255) NOT NULL,
    INN BIGINT NOT NULL,
    KPP BIGINT NOT NULL,
    INDUSTRY VARCHAR(255) NOT NULL,
    PHONE BIGINT NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    REVENUE BIGINT NOT NULL
);

CREATE TABLE users(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL
);

CREATE TABLE statement(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CREATED_BY INT NOT NULL,
    COUNT_MONTH INT NOT NULL,
    COUNT_CONTACT INT NOT NULL,
    COUNT_COMPANY INT NOT NULL,
    MONEY_TURNOVER BIGINT NOT NULL,
    COMMENT TEXT NULL
);


ALTER TABLE
    crm_deal ADD CONSTRAINT crm_deal_responsible_id_foreign FOREIGN KEY(RESPONSIBLE_ID) REFERENCES users(ID);
ALTER TABLE
    crm_deal ADD CONSTRAINT crm_deal_company_id_foreign FOREIGN KEY(COMPANY_ID) REFERENCES company(ID);